language: php

php:
  - 7.2

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction -o

script:
  - composer lint
  - composer stan
  - composer cs
  - composer test