language: php

php:
  - 7.2

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction -o

script:
  - composer lint
  - composer stan
  - composer cs
  - composer test-coverage

after_script:
  - composer global require php-coveralls/php-coveralls ^2.1.0
  - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

sudo: false

cache:
  directories:
    - $HOME/.composer/cache